---
- name: Create the directory for Docker compose
  file:
    path: "{{ ansible_env.HOME }}/docksible"
    state: directory
    mode: '0755'

- name: Create the directory tree for Docker volumes
  file:
    path: "{{ ansible_env.HOME }}/docksible-volumes/{{ item }}"
    state: directory
    mode: '0755'
                                                   # TODO: Do the proxy service also??!
  # TODO: dashes in filepaths
  loop: [ 'db_data', 'wordpress_data', 'nginx_data', 'ssh-proxy_data' ]

- name: Copy the Nginx Configuration
  template:
      src: "nginx.conf.j2"
      dest: "{{ ansible_env.HOME }}/docksible-volumes/nginx_data/nginx.conf"
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      mode: '0644'

- name: Load Docker-Compose file for WordPress
  template:
      src: docker-compose-wordpress.yml.j2
      dest: "$HOME/docksible/docker-compose-wordpress.yml"
      owner: root
      group: root
      mode: '0644'

- name: Run WordPress
  raw: "cd $HOME/docksible; docker-compose -f docker-compose-wordpress.yml up -d"
