---
- name: Create the directory for Docker compose
  file:
    path: "{{ ansible_env.HOME }}/docksible"
    state: directory
    mode: '0755'

- name: Create the directory tree for Docker volumes
  file:
    path: "{{ ansible_env.HOME }}/docksible-volumes/{{ item }}"
    state: directory
    mode: '0755'
  # TODO: dashes in filepaths
  loop: [ 'db_data', 'wordpress_data', 'nginx_data', 'ssh-proxy-data' ]

- name: Copy the Nginx Configuration
  template:
      src: "nginx.conf.j2"
      dest: "{{ ansible_env.HOME }}/docksible-volumes/nginx_data/nginx.conf"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'

- name: Load Docker-Compose file for WordPress
  template:
      src: docker-compose-wordpress.yml.j2
      dest: "$HOME/docksible/docker-compose-wordpress.yml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0600'

  # TODO: See GH #45.
- name: Run WordPress
  raw: "docker compose -f {{ ansible_env.HOME }}/docksible/docker-compose-wordpress.yml up -d"
